name: "BioCoDE: Biomedical & Computational Discovery Experience"
description: ""

url: "https://biocode.github.io"

gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
