name: GitHub Pages Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Jekyll (if you're using Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Build and deploy to GitHub Pages
        run: |
          bundle install
          bundle exec jekyll build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
